# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "integration-tests/"
    groups:
      # Update all npm dependencies together
      # https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/
      "NPM dependencies":
        "patterns":
          - "*"

    schedule:
      interval: "daily"
