# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Commit message lint
permissions:
  contents: read

on:
  pull_request: ~

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    name: commitlint
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
