# https://github.com/marketplace/actions/luarocks-tag-release
name: LuaRocks release
on:
  pull_request: # Will test a local install without uploading to luarocks.org
  workflow_dispatch: # makes it possible to run the workflow manually
  release:
    types:
      # Will upload to luarocks.org when a release is made
      - published

jobs:
  luarocks-release:
    runs-on: ubuntu-24.04
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@adbca66e871a519055f4917c6af5fbf19f656f5d # v7.2.0
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          # https://github.com/marketplace/actions/luarocks-tag-release#dependencies
          dependencies: |
            plenary.nvim
