---
name: Type check
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Type check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: stevearc/nvim-typecheck-action@v2
        with:
          path: lua
          level: Information
          libraries:
            # space separated
            https://github.com/nvim-lua/plenary.nvim
            https://github.com/folke/snacks.nvim
          # allow failing until https://github.com/stevearc/nvim-typecheck-action/issues/5 is resolved
          luals-version: 3.15.0
